#попытки подключить postgresql

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portal
    username: root
    password: 050514
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
